import { Product, Sale, CustomerKhata, ShopSettings } from '@/types';

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod_shan_masala',
    name: 'Shan Bombay Biryani Masala 50g',
    nameUrdu: 'شان بمبئی بریانی مصالحہ',
    price: 140,
    costPrice: 115,
    stock: 45,
    category: 'Spices',
    unit: 'packet',
    barcode: '896400000101',
    createdAt: Date.now() - 30 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_olpers_milk',
    name: "Olper's Milk 1 Litre Full Cream",
    nameUrdu: 'اولپرز دودھ 1 لیٹر',
    price: 290,
    costPrice: 255,
    stock: 32,
    category: 'Dairy',
    unit: 'litre',
    barcode: '896400000202',
    createdAt: Date.now() - 25 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_tapal_tea',
    name: 'Tapal Danedar Tea 950g Pack',
    nameUrdu: 'تپال دانے دار چائے 950 گرام',
    price: 1550,
    costPrice: 1380,
    stock: 18,
    category: 'Kiryana',
    unit: 'packet',
    barcode: '896400000303',
    createdAt: Date.now() - 20 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_habib_oil',
    name: 'Habib Cooking Oil 5 Litre Can',
    nameUrdu: 'حبیب ککنگ آئل 5 لیٹر کین',
    price: 2650,
    costPrice: 2400,
    stock: 12,
    category: 'Grocery',
    unit: 'litre',
    barcode: '896400000404',
    createdAt: Date.now() - 18 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_pepsi_15l',
    name: 'Pepsi 1.5 Litre Bottle',
    nameUrdu: 'پیپسی 1.5 لیٹر بوتل',
    price: 180,
    costPrice: 150,
    stock: 24,
    category: 'Beverages',
    unit: 'piece',
    barcode: '896400000505',
    createdAt: Date.now() - 15 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_lays_masala',
    name: 'Lays French Cheese Large 60g',
    nameUrdu: 'لیز فرینچ چیز 60 گرام',
    price: 100,
    costPrice: 82,
    stock: 50,
    category: 'Snacks',
    unit: 'packet',
    barcode: '896400000606',
    createdAt: Date.now() - 12 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_rooh_afza',
    name: 'Rooh Afza Syrup 800ml Bottle',
    nameUrdu: 'روح افزا 800 ملی لیٹر',
    price: 420,
    costPrice: 360,
    stock: 15,
    category: 'Beverages',
    unit: 'piece',
    barcode: '896400000707',
    createdAt: Date.now() - 10 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_national_ketchup',
    name: 'National Tomato Ketchup 500g Pouch',
    nameUrdu: 'نیشنل ٹماٹو کیچپ 500 گرام',
    price: 320,
    costPrice: 275,
    stock: 20,
    category: 'Grocery',
    unit: 'packet',
    barcode: '896400000808',
    createdAt: Date.now() - 8 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_dawn_bread',
    name: 'Dawn Plain Bread Family Size',
    nameUrdu: 'ڈان پلین بریڈ فیملی سائز',
    price: 210,
    costPrice: 180,
    stock: 8,
    category: 'Bakery',
    unit: 'piece',
    barcode: '896400000909',
    createdAt: Date.now() - 5 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
  {
    id: 'prod_lux_soap',
    name: 'Lux Velvet Touch Soap 140g',
    nameUrdu: 'لکس صابن 140 گرام',
    price: 160,
    costPrice: 135,
    stock: 35,
    category: 'Personal Care',
    unit: 'piece',
    barcode: '896400001010',
    createdAt: Date.now() - 2 * 86400000,
    updatedAt: Date.now(),
    syncStatus: 'synced',
  },
];

export const SAMPLE_KHATA: CustomerKhata[] = [
  {
    id: 'cust_tariq_mahmood',
    name: 'Tariq Mahmood (Street 4)',
    nameUrdu: 'طارق محمود (گلی نمبر 4)',
    phone: '03001234567',
    address: 'House #42, Block C, Satellite Town',
    totalDebt: 3450,
    lastUpdated: Date.now() - 3600000 * 4,
    syncStatus: 'synced',
    transactions: [
      {
        id: 'tx_tm_1',
        date: new Date(Date.now() - 86400000 * 4).toISOString(),
        type: 'credit',
        amount: 4500,
        note: 'Grocery & Oil purchase on credit',
      },
      {
        id: 'tx_tm_2',
        date: new Date(Date.now() - 86400000 * 2).toISOString(),
        type: 'payment',
        amount: 1050,
        note: 'Cash payment received via EasyPaisa',
      },
    ],
  },
  {
    id: 'cust_muhammad_ali',
    name: 'Muhammad Ali (Tailor Shop)',
    nameUrdu: 'محمد علی (درزی)',
    phone: '03219876543',
    address: 'Shop 12, Main Bazaar',
    totalDebt: 1820,
    lastUpdated: Date.now() - 3600000 * 12,
    syncStatus: 'synced',
    transactions: [
      {
        id: 'tx_ma_1',
        date: new Date(Date.now() - 86400000 * 5).toISOString(),
        type: 'credit',
        amount: 2500,
        note: 'Monthly ration items',
      },
      {
        id: 'tx_ma_2',
        date: new Date(Date.now() - 86400000 * 1).toISOString(),
        type: 'payment',
        amount: 680,
        note: 'Partial cash payment',
      },
    ],
  },
  {
    id: 'cust_choudhry_usman',
    name: 'Choudhry Usman',
    nameUrdu: 'چوہدری عثمان',
    phone: '03335554433',
    address: 'Farm House #7, Colony',
    totalDebt: 850,
    lastUpdated: Date.now() - 86400000 * 3,
    syncStatus: 'synced',
    transactions: [
      {
        id: 'tx_cu_1',
        date: new Date(Date.now() - 86400000 * 3).toISOString(),
        type: 'credit',
        amount: 850,
        note: 'Beverages and snacks for event',
      },
    ],
  },
];

export function generateDemoSales(products: Product[]): Sale[] {
  const p1 = products[0] || SAMPLE_PRODUCTS[0];
  const p2 = products[1] || SAMPLE_PRODUCTS[1];
  const p3 = products[2] || SAMPLE_PRODUCTS[2];
  const p4 = products[3] || SAMPLE_PRODUCTS[3];
  const p5 = products[4] || SAMPLE_PRODUCTS[4];

  const now = Date.now();
  const DAY = 86400000;

  return [
    {
      id: 'sale_inv_1001',
      billNumber: 'INV-1001',
      date: new Date(now - 3600000 * 2).toISOString(),
      customerName: 'Tariq Mahmood',
      customerPhone: '03001234567',
      items: [
        { product: p1, quantity: 2, unitPrice: p1.price, total: p1.price * 2 },
        { product: p2, quantity: 1, unitPrice: p2.price, total: p2.price },
      ],
      subtotal: p1.price * 2 + p2.price,
      discount: 20,
      discountType: 'fixed',
      grandTotal: p1.price * 2 + p2.price - 20,
      totalProfit: (p1.price - (p1.costPrice || 0)) * 2 + (p2.price - (p2.costPrice || 0)),
      paymentMethod: 'cash',
      amountPaid: 600,
      change: 600 - (p1.price * 2 + p2.price - 20),
      createdAt: now - 3600000 * 2,
      syncStatus: 'synced',
    },
    {
      id: 'sale_inv_1002',
      billNumber: 'INV-1002',
      date: new Date(now - 3600000 * 5).toISOString(),
      customerName: 'Muhammad Ali',
      customerPhone: '03219876543',
      items: [
        { product: p3, quantity: 1, unitPrice: p3.price, total: p3.price },
        { product: p5, quantity: 2, unitPrice: p5.price, total: p5.price * 2 },
      ],
      subtotal: p3.price + p5.price * 2,
      discount: 0,
      discountType: 'fixed',
      grandTotal: p3.price + p5.price * 2,
      totalProfit: (p3.price - (p3.costPrice || 0)) + (p5.price - (p5.costPrice || 0)) * 2,
      paymentMethod: 'udhaar',
      createdAt: now - 3600000 * 5,
      syncStatus: 'synced',
    },
    {
      id: 'sale_inv_1003',
      billNumber: 'INV-1003',
      date: new Date(now - DAY * 1 - 3600000 * 3).toISOString(),
      customerName: 'Walk-in Customer',
      items: [
        { product: p4, quantity: 1, unitPrice: p4.price, total: p4.price },
      ],
      subtotal: p4.price,
      discount: 50,
      discountType: 'fixed',
      grandTotal: p4.price - 50,
      totalProfit: (p4.price - (p4.costPrice || 0)) - 50,
      paymentMethod: 'online',
      createdAt: now - DAY * 1 - 3600000 * 3,
      syncStatus: 'synced',
    },
    {
      id: 'sale_inv_1004',
      billNumber: 'INV-1004',
      date: new Date(now - DAY * 2 - 3600000 * 6).toISOString(),
      customerName: 'Choudhry Usman',
      customerPhone: '03335554433',
      items: [
        { product: p2, quantity: 2, unitPrice: p2.price, total: p2.price * 2 },
        { product: p5, quantity: 3, unitPrice: p5.price, total: p5.price * 3 },
      ],
      subtotal: p2.price * 2 + p5.price * 3,
      discount: 0,
      discountType: 'fixed',
      grandTotal: p2.price * 2 + p5.price * 3,
      totalProfit: (p2.price - (p2.costPrice || 0)) * 2 + (p5.price - (p5.costPrice || 0)) * 3,
      paymentMethod: 'cash',
      amountPaid: 1200,
      change: 1200 - (p2.price * 2 + p5.price * 3),
      createdAt: now - DAY * 2 - 3600000 * 6,
      syncStatus: 'synced',
    },
  ];
}
